services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./seeds.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    stdin_open: true
    tty: true

volumes:
  db:
