name: CI & CD

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Install dependencies
        run: npm ci

      - name: Execute
        run: npm run lint
